stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Construction du projet..."

test_job:
  stage: test
  script:
    - echo "Exécution des tests..."

deploy_job:
  stage: deploy
  script:
    - echo "Déploiement du projet..."